#!/bin/bash

mem() {
    mem="$(awk '/^Mem/ {print $3}' <(free -m))"
    printf "%b" "$mem"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu="$((100*( (total-prevtotal) - (idle - previdle) ) / (total-prevtotal) ))"
    printf "%b" "$cpu"
}

hdd() {
  hd=( $(awk '
    {i=$5} /boot/ {a=i}; /root/ {b=i}; /home/ {c=i}; /media/ {d=i}
    END {if (NR>=11) print a,b,c,d; else print a,b,c}
           ' <(df -P)) )
  drives="${#hd[@]}"
  if (( drives > 3 )); then
    printf "%b" "${hd[@]:0:3} ${hd[@]:3:1}"
  else
    printf "%b" "${hd[@]}"
  fi  
}

int() {
	host google.com > /dev/null &&
	printf "%b" "ON" || printf "%b" "NO"
}

dte() {
	dte="$(date "+%H:%M")"
	printf "%b" "$dte"
}

xsetroot -name "CPU $(cpu) MEM $(mem) • HDD $(hdd) • NET $(int) • $(dte) "
